# Generated by Django 2.2.13 on 2020-11-30 15:52

from django.conf import settings
import django.contrib.sites.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
from promgen import util


def change_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.get(id=settings.SITE_ID)
    site.domain = util.setting("site.domain", 'promgen.service.com')
    site.name = 'promgen'
    site.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promgen', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_site_name)
    ]
